name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install @progress/kendo-licensing
        run: npm install --no-save @progress/kendo-licensing

      - name: Configure KendoReact license
        run: npx kendo-ui-license activate --license "${{ secrets.TELERIK_LICENSE }}" --email "nanz@progress.com"
        env:
          HOME: /home/runner

      - name: Check Telerik license file
        run: ls -al ~/.telerik || echo "No license file found"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
